main: de.n1ck145.lobbySystem.main.Main
version: 1.1.1
name: LobbySystem
author: N1CK145

commands:
    spawn:
        description: Teleports you to spawn
        aliases: [l, lobby, hub]
    lobbyc:
        description: Configure the plugin
    build:
        description: Allows you to build!
    message:
        description: 
        aliases: [msg]