main: de.n1ck145.lobbySystem.main.Main
version: 1.2.0
name: LobbySystem
author: N1CK145

commands:
    spawn:
        description: Teleports you to spawn
        aliases: [l, lobby, hub]
    lobbyc:
        description: Configure the plugin
    build:
        description: build [player]
    message:
        description: 
        aliases: [msg]
    warp:
        description: warp <warp>
    setwarp:
        description: setwarp <warp>

permissions:
    lobbySystem.*:
        description: Gives all LobbySystem permissions
        children:
            lobbySystem.coins.*: true
            lobbySystem.cmd.*: true
    
    lobbySystem.cmd.*:
        description: Gives permissions to all LobbySystem commands
        children:
            lobbySystem.cmd.spawn: true
            lobbySystem.cmd.message: true
            lobbySystem.cmd.warp: true
            lobbySystem.cmd.build: true
            lobbySystem.cmd.build.other: true
            lobbySystem.cmd.admin: true
            lobbySystem.cmd.setwarp: true